group: "lapo-unweighted"
seed: 0

lapo:
  num_epochs: 10
  batch_size: 512
  future_obs_offset: 10
  learning_rate: 0.0001
  weight_decay: 0.0
  warmup_epochs: 3
  latent_action_dim: 16  # originally: 8192
  encoder_scale: 6 # originally: 6
  encoder_num_res_blocks: 2 # originally: 2
  encoder_deep: False
  frame_stack: 3
  data_path: "/data/tucana/ms24ha/64px_data_chunked/hopper-hop-scale-easy-video-hard-64px-5k.hdf5"

bc:
  num_epochs: 10
  batch_size: 512
  learning_rate: 0.0001
  weight_decay: 0.0 
  warmup_epochs: 0
  encoder_scale: 32 # originally: 32, or 8
  encoder_num_res_blocks: 2 # originally: 2
  encoder_deep: False
  dropout: 0.0
  use_aug: False
  frame_stack: 3
  data_path: "/data/tucana/ms24ha/64px_data_chunked/hopper-hop-scale-easy-video-hard-64px-5k.hdf5"
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 5
  eval_seed: 0

decoder:
  total_updates: 2500
  batch_size: 512
  learning_rate: 0.0003
  weight_decay: 0.0
  warmup_epochs: 0
  hidden_dim: 256 # originally: 256
  use_aug: False
  data_path: "/data/tucana/ms24ha/64px_data_chunked/hopper-hop-scale-easy-video-hard-labeled-1000x16-64px.hdf5"
  dcs_backgrounds_path: "DAVIS/JPEGImages/480p"
  dcs_backgrounds_split: "train"
  eval_episodes: 25
  eval_seed: 0

